{{- if .Values.apiGateway.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gpu-telemetry.fullname" . }}-api-gateway
  labels:
    {{- include "gpu-telemetry.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
spec:
  type: {{ .Values.apiGateway.service.type }}
  ports:
  - port: {{ .Values.apiGateway.service.port }}
    targetPort: {{ .Values.apiGateway.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "gpu-telemetry.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
{{- end }}
