{{- if .Values.queueService.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gpu-telemetry.fullname" . }}-queue-service
  labels:
    {{- include "gpu-telemetry.labels" . | nindent 4 }}
    app.kubernetes.io/component: queue-service
spec:
  type: {{ .Values.queueService.service.type }}
  ports:
  - port: {{ .Values.queueService.service.port }}
    targetPort: {{ .Values.queueService.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "gpu-telemetry.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: queue-service
{{- end }}
